"""Initial MS SQL migration

Revision ID: 73246a118152
Revises: 2fbac5462ce3
Create Date: 2026-03-22 19:24:46.309702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '73246a118152'
down_revision: Union[str, Sequence[str], None] = '2fbac5462ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_api_key_hash'), 'projects', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('dynamic_records',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dynamic_records_id'), 'dynamic_records', ['id'], unique=False)
    op.create_index(op.f('ix_dynamic_records_project_id'), 'dynamic_records', ['project_id'], unique=False)
    op.create_index(op.f('ix_dynamic_records_resource_name'), 'dynamic_records', ['resource_name'], unique=False)
    op.create_table('resource_registry',
    sa.Column('project_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'resource_name')
    )
    op.drop_table('Experiments')
    op.drop_table('Dataset')
    op.drop_table('Vehicle')
    op.drop_table('Project')
    op.drop_table('uad_projects')
    op.drop_table('User')
    op.drop_table('Route')
    op.drop_table('RouteCost')
    op.drop_table('Metric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Metric',
    sa.Column('MetricID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ExperimentID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MetricName', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('MetricValue', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('RecordedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ExperimentID'], ['Experiments.ExperimentID'], name=op.f('FK_Metric_Experiments')),
    sa.PrimaryKeyConstraint('MetricID', name=op.f('PK_Metric'))
    )
    op.create_table('RouteCost',
    sa.Column('CostID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('RouteID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('FuelCost', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('TollCost', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('FoodCost', sa.DECIMAL(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('TotalCost', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('CalculatedAt', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['RouteID'], ['Route.RouteID'], name=op.f('FK_RouteCost_Route')),
    sa.PrimaryKeyConstraint('CostID', name=op.f('PK_RouteCost'))
    )
    op.create_table('Route',
    sa.Column('RouteID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SourceLocation', sa.TEXT(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('DestinationLocation', sa.TEXT(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Distance', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ProjectID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('VehicleID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ProjectID'], name=op.f('FK_Route_Project')),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name=op.f('FK_Route_User')),
    sa.ForeignKeyConstraint(['VehicleID'], ['Vehicle.VehicleId'], name=op.f('FK_Route_Vehicle')),
    sa.PrimaryKeyConstraint('RouteID', name=op.f('PK_Route'))
    )
    op.create_table('User',
    sa.Column('UserID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.TEXT(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Email', sa.TEXT(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('UserID', name=op.f('PK_User'))
    )
    op.create_table('uad_projects',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('is_active', mssql.BIT(), autoincrement=False, nullable=False),
    sa.Column('config_json', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('owner_user_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__uad_proj__3213E83F9F195AB7'))
    )
    op.create_table('Project',
    sa.Column('ProjectID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ProjectName', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Description', sa.TEXT(length=16, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('UserID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['User.UserID'], name=op.f('FK_Project_User')),
    sa.PrimaryKeyConstraint('ProjectID', name=op.f('PK_Project'))
    )
    op.create_table('Vehicle',
    sa.Column('VehicleId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('VehicleType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('FuelType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Mileage', sa.FLOAT(precision=53), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('VehicleId', name=op.f('PK_Vehicle'))
    )
    op.create_table('Dataset',
    sa.Column('DatasetID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('DatasetName', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('DatasetType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Source', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('CreatedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('DatasetID', name=op.f('PK_Dataset'))
    )
    op.create_table('Experiments',
    sa.Column('ExperimentID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ProjectID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DatasetID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ModelName', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('AlgorithumType', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('CreatedAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DatasetID'], ['Dataset.DatasetID'], name=op.f('FK_Experiments_Dataset')),
    sa.ForeignKeyConstraint(['ProjectID'], ['Project.ProjectID'], name=op.f('FK_Experiments_Project')),
    sa.PrimaryKeyConstraint('ExperimentID', name=op.f('PK_Experiments'))
    )
    op.drop_table('resource_registry')
    op.drop_index(op.f('ix_dynamic_records_resource_name'), table_name='dynamic_records')
    op.drop_index(op.f('ix_dynamic_records_project_id'), table_name='dynamic_records')
    op.drop_index(op.f('ix_dynamic_records_id'), table_name='dynamic_records')
    op.drop_table('dynamic_records')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_api_key_hash'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
